### PR TITLE
add missing dependency

### PR DESCRIPTION
**Pull request by xdbr**
dependency to bluebird was missing

### CODE REVIEW

**Comment by tomatau** [comment]
Works for me without this dependency, no errors

**Comment by xdbr** [comment]
I think I've seen this with `npm test` but forgot to open a different bug for it – feel free to close if not applicable. Can't test this again currently

**Comment by tomatau** [comment]
OK thanks, if you could remember some repro steps then I'd be very interested, want to make sure this project runs smoothly throughout!

I'm going to close this as I'm planning an upgrade to babel6 which may change the dependencies for promise integration.

Right now I have working tests both with and without bluebird installed locally.

**Pull request closed without merging**
